/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package my.kotlin.sandbox

import java.util.Date

class App {
    val greeting: String
        get() {
            return "Hello World ${ java.util.Date() }!"
        }
}

fun main() {
    println(App().greeting)
    println(App().greeting)
    println(App().greeting)
    println("MOIN")
    println(App().greeting)
}
